<?php
//get active page details
$arr_active_page = $this->navigation()->findActive("navigation");
if (isset($arr_active_page["page"]))
{
	$objActivePage = $arr_active_page["page"];
} else {
	$objActivePage = FALSE;
}//end if

if ($objActivePage instanceof \Zend\Navigation\Page\Mvc && $objActivePage->getRoute() != "home")
{
	//cache menu output for javascript
	ob_start();
?>

<!--<nav class="mj3-sidebar hidden-print hidden-xs hidden-sm">
	<ul class="nav bs-docs-sidenav">
		<?php
		$objUser = \FrontUserLogin\Models\FrontUserSession::isLoggedIn();

// 		if ($objActivePage->hasChildren())
// 		{
// 			//load parent link
// 			if (!$objActivePage->getParent() instanceof \Zend\Navigation\Navigation && $objActivePage->getParent()->getRoute() != "home")
// 			{
// 				echo "<li class=\"active\"><a href=\"" . $this->url($objActivePage->getParent()->getRoute()) . "\" title=\"" . $objActivePage->getParent()->getLabel() . "\" data-toggle=\"tooltip\">" . $objActivePage->getParent()->getLabel() . "</a></li>";
// 			}//end if

// 			foreach ($objActivePage->getPages() as $objPage)
// 			{
// 				echo "<li><a href=\"" . $this->url($objPage->getRoute()) . "\" title=\"" . $objPage->getLabel() . "\" data-toggle=\"tooltip\">" . $objPage->getLabel() . "</a></li>";
// 			}//end foreach
// 		} else {
// 			//use parents children to generate menu
// 			if (!$objActivePage->getParent() instanceof \Zend\Navigation\Navigation && $objActivePage->getParent()->getRoute() != "home")
// 			{
// 				//insert parent link
// 				echo "<li><a href=\"" . $this->url($objActivePage->getParent()->getRoute()) . "\" title=\"" . $objActivePage->getParent()->getLabel() . "\" data-toggle=\"tooltip\">" . $objActivePage->getParent()->getLabel() . "</a></li>";
// 			}//end if

// 			//process children
// 			foreach ($objActivePage->getParent()->getPages() as $objPage)
// 			{
// 				if ($objPage->isActive())
// 				{
// 					$active = "active";
// 				} else {
// 					$active = "";
// 				}//end if

// 				$generate = FALSE;
// 				switch (strtolower($objPage->getLabel()))
// 				{
// 					case "campaigns":
// 						if (in_array("campaigns", $objUser->profile->plugins_enabled))
// 						{
// 							$generate = TRUE;
// 						}//end if
// 						break;

// 					case "file manager":
// 						if (in_array("file_library", $objUser->profile->plugins_enabled))
// 						{
// 							$generate = TRUE;
// 						}//end if
// 						break;

// 					case "webhooks":
// 						if (in_array("webhooks", $objUser->profile->plugins_enabled))
// 						{
// 							$generate = TRUE;
// 						}//end if
// 						break;

// 					case "inbox":
// 						if (in_array("inbox", $objUser->profile->plugins_enabled))
// 						{
// 							$generate = TRUE;
// 						}//end if
// 						break;

// 					default:
// 						$generate = TRUE;
// 						break;
// 				}//end switch

// 				if ($generate === TRUE)
// 				{
// 					echo "<li class=\"$active\"><a href=\"" . $this->url($objPage->getRoute()) . "\" title=\"" . $objPage->getLabel() . "\" data-toggle=\"tooltip\">" . $objPage->getLabel() . "</a></li>";
// 				}//end if
// 			}//end foreach
// 		}//end if
		?>
	</ul>
</nav>-->

<?php
$nav_menu = ob_get_contents();
ob_end_clean();
//inject javascript to dock the menu
?>
<script type="text/javascript">
// 	jQuery(document).ready(function () {
// 		jQuery.mj_docker({
// 			dock_title : false,
// 			dock_collapse : false,
//			dock_content : '<?php echo str_replace("\n", "", $nav_menu); ?>',
// 			dock_region : "m3-content-section-east",
// 			dock_position : 0
// 		});
// 	});
</script>
<?php
}//end if

/**
 * Newsfeeder
 */
// if ($this->resolver("front-newsfeed-panel") && isset($this->app_config["profile_config"]["news_feed_credentials"]))
// {
// 	echo $this->render("front-newsfeed-panel");
// }//end if

