<?php
echo $this->doctype();

if (!is_object($this->objProfileSettings))
{
	//load native profile settings
	$this->objProfileSettings = \FrontProfileSettings\Models\NativeProfileSettingsModel::readProfileSettings();
}//end if

//set page title
if (isset($this->app_config["profile_config"]["profile_title"]))
{
	$profile_title = $this->app_config["profile_config"]["profile_title"];
} else {
	$profile_title = "Majestic 3";
}//end if


//set page title
if (is_object($this->objProfileSettings))
{
	$profile_title = $this->objProfileSettings->get("profile_title", $profile_title);
}//end if

//load css
$icon = $this->layout()->cdn_url . "/images/m3frontend/favicon.ico"; //set default icon
if (isset($this->app_config["login_page_settings"]["fav_icon"]) && $this->app_config["login_page_settings"]["fav_icon"] != "")
{
	$icon = $this->app_config["login_page_settings"]["fav_icon"];
}//end if

if (is_object($this->objProfileSettings))
{
	$icon = $this->objProfileSettings->get("profile_icon", $icon);
}//end if
ini_set('display_errors', 1);

if (isset($this->angular_app_name) && $this->angular_app_name != '')
{
	$angular_app_name = $this->angular_app_name;
} else {
	$angular_app_name = FALSE;
}//end if
?>
<html leng="en">
	<head>
		<?php echo $this->headTitle($this->translate($profile_title))->setSeparator(' - ')->setAutoEscape(false);?>
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/jquery/jquery-2.1.1.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript">
			//define some global javascript vars
			var global_wait_image = "<img src=\"<?php echo $this->layout()->cdn_url;?>/images/m3frontend/animations/please_wait.gif\" />";
			var cdn_url = '<?php echo $this->layout()->cdn_url; ?>';
		</script>


		<!--[if lt IE 9]><script type="text/javascript" src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
		<!--[if lt IE 9]><script type="text/javascript" src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script><![endif]-->
		<?php
			//set metatags
			echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
			echo $this->headLink(array("rel" => "shortcut icon", "type" => "image/vnd.microsoft.icon", "href" => $icon))
				->appendStylesheet($this->layout()->cdn_url . "/bootstrap/css/bootstrap.min.css")
				->appendStylesheet($this->layout()->cdn_url . "/bootstrap/bootstrap-datepicker/dist/css/bootstrap-datepicker3.standalone.min.css")
				->appendStylesheet($this->basePath() . '/css/main.css')
				->appendStylesheet($this->basePath() . '/js/angular/helpers/angular-styles.css')
			;

			//include basic angular files
			echo $this->partial('layout/angular/basic');
		?>
		<script type="text/javascript">

			function resizeFullScreen(element)
			{
console.log('2');
				//get target
				var target_element = element.attr('data-resize-target');
				jQuery(target_element).toggleClass('container-full-height container-full-width');
			}//end function

			function resizeHeight(element)
			{
console.log('3');
				//get target
				var target_element = element.attr('data-resize-target');
				jQuery(target_element).toggleClass('container-full-height');
			}//end function

			function resizeWidth(element)
			{
console.log('4');
				//get target
				var target_element = element.attr('data-resize-target');
				jQuery(target_element).toggleClass('container-full-width');
			}//end function
		</script>
	</head>
	<body>
		<div class="primary-app-container" <?php if ($angular_app_name !== false && $angular_app_name != '') { echo 'ng-app="' . $angular_app_name . '"';} ?>>
				<!-- First Level Navigation -->
				<?php
				if (!isset($this->angular_disable_main_menu))
				{
					//insert first level navigation
					echo $this->partial("layout/navigation-first-level");
				}//end if
				?>
				<!-- First Level Navigation ends -->

			<div class="wrapper">

				<!-- Main content -->
				<div class="col-md-9 m3-content-section-main" role="main">
					<div class="bs-docs-section">
					<?php
						echo $this->partial("layout/body-pane");
					?>
					</div>
				</div>
			</div>
		</div>
		
		<?php 
			if ($_GET['debug_display_errors'] == 1)
			{
				echo '<!-- Reported Errors....';
				echo $this->partial("layout/api-data");
				echo $this->partial("layout/query-details");
				echo '-->';
			}//end if
		?>
	</body>
</html>