<script src="/js/angular/helpers/helper.js"></script>
<script src="/js/main.js"></script>

<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-route.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-resource.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-cookies.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-sanitize.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-animate.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-messages.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/bootstrap/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/smart-table/smart-table.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/api-check/api-check.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/formly/formly.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/formly/angular-formly-templates-bootstrap/angular-formly-templates-bootstrap.min.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/promise-tracker/promise-tracker.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/paginator/dirPagination.js"></script>
<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/angular-confirm/dist/angular-confirm.min.js"></script>

<link rel="stylesheet" href="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/angular-motion/angular-motion.min.css">
<link rel="stylesheet" href="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/angular-motion/modules/collapse.min.css">
<link rel="stylesheet" href="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/angular-confirm/dist/angular-confirm.min.css">
<?php
echo $this->partial('layout/angular/notices');
?>