<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_MEDIUM_SMS_HTML .'&nbsp; Edit SMS Account'); ?>
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-sms-accounts-admin"); ?>" title="Back" data-toggel="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>

	<div class="mj3_forms clearfix">
		<?php
			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this, array("enable_accordion" => TRUE, "generate_field_groups" => TRUE));
		?>
	</div>

</div>

