<script type="text/javascript">
	var global_page_config = {
		cdnLocation: '<?php echo $this->layout()->cdn_url; ?>',
		pageTitle: '<?php echo $this->renderStandardViewHeader(ICON_LARGE_PIE_CHART_HTML .'&nbsp; Basic Report Viewer'); ?>',
	};
</script>
<script src="/js/angular/reports-basic/app.js"></script>
<script src="/js/angular/reports-basic/controllers.js"></script>
<script src="/js/angular/reports-basic/services.js"></script>
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/tabletools/2.2.4/js/dataTables.tableTools.min.js"></script>

<!-- datatable download capabilities -->
<script src="//cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>

<link rel="css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="css" href="//cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">

<?php
echo '<div ng-app="frontBasicReportViewerApp"><div ng-view></div></div>';
return;