<div class="mj3_tables clearfix">
	<?php echo $this->renderStandardViewHeader(ICON_MEDIUM_USER_DATA_ACL_HTML .'&nbsp; Role Acl Links Administration - Remove Resource'); ?>
	
	<div class="mj3_forms clearfix">
		<form method="post">
			<h3>Are you sure you want to delete a Role Resource? This action cannot be undone and the effect is immediate</h3>
			<input type="submit" name="delete" value="Yes" class="btn btn-danger"/>
			<input type="submit" value="Cancel" class="btn btn-success"/>
		</form>
	</div>
</div>