<div class="mj3_tables clearfix">
<?php
echo $this->renderStandardViewHeader(ICON_MEDIUM_USER_DATA_ACL_HTML .'&nbsp; Update Role Acl Resource Link');
?>

	<ul class="nav nav-tabs">
		<li role="presentation">
			<?php echo "<a href=\"" . $this->url("front-role-acl-links/admin", array("role_id" => $this->objRole->id, "action" => "list-acl-resources")) . "\" title=\"Back\" data-toggle=\"tooltip\">" . ICON_MEDIUM_BACK_HTML . "</a>";?>
		</li>
	</ul>
	<div class="mj3_table_contain clearfix">
	<?php
		//display role information
		echo "<fieldset><legend>Role : " . $this->objRole->get("role_name") . "</legend>";
		echo "Role Name : " . $this->objRole->get("role_name") . "<br>";
		echo "Role Description : " . $this->objRole->get("role_description") . "<br>";
		echo "Role Active : " . $this->objRole->get("role_active") . "<br>";
		echo "Role Run Level : " . $this->objRole->get("role_acl_run_level") . "<br>";
		echo "</fieldset>";
		echo "</div>";

		echo "<div class=\"mj3_forms clearfix\">";
		$form = $this->form;
		$form->prepare();
		echo $this->renderSystemFormHelper($form, $this);
	?>
	</div>
</div>