<div class="mj3_tables clearfix">

<?php
echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML . '&nbsp; Create Journey');
?>
	<script type="text/javascript">	
		jQuery(document).ready(function () {
			//lazyload additional files
			LazyLoad.js([
			    '<?php echo $this->layout()->cdn_url . '/js/includes/journeys-admin.js' ?>',
			]);
		});
	</script>
	
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-comms-admin/journeys"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>
	<div class="mj3_forms clearfix">

		<?php
			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this, array("generate_field_groups" => TRUE, "enable_accordion" => TRUE));
		?>

	</div>

</div>