<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML . ' &nbsp; Delete Journey'); ?>
	<div class="mj3_forms clearfix">

		<form method="post">

			<h3>Are you sure you want to delete "<?php echo $this->objJourney->get("journey");?>"?<br />
			This action cannot be undone.</h3>
			<input type="submit" value="Yes" name="delete" class="btn btn-danger"/>
			<input type="submit" value="Cancel" class="btn btn-success"/>

		</form>

	</div>

</div>