<div class="mj3_tables clearfix">

<?php
echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML . ' &nbsp; Edit Journey');
?>
	<script type="text/javascript">	
		jQuery(document).ready(function () {
			//lazyload additional files
			LazyLoad.js([
			    '<?php echo $this->layout()->cdn_url . '/js/includes/journeys-admin.js' ?>',
			]);
		});
	</script>
	
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-comms-admin/journeys"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
		<li role="presentation"><a href="<?php echo $this->url("front-comms-admin/comms", array("journey_id" => $this->objJourney->id)); ?>" title="View / Edit specific Communications" data-toggle="tooltip"><?php echo ICON_LARGE_LOAD_HTML; ?></a></li>
	</ul>

	<div class="mj3_forms clearfix">

		<?php

		$form = $this->form;
		$form->prepare();
		echo $this->renderSystemFormHelper($form, $this, array("generate_field_groups" => TRUE, "enable_accordion" => TRUE));
		?>

	</div>

</div>