<div class="mj3_tables clearfix">
<?php
	echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML .'&nbsp;Delete Communication');
?>
	<div class="mj3_forms clearfix">

		<form method="post">
			<h3>Are you sure you want to remove the allocated communication?<br />This action cannot be undone.</h3>
			<input type="submit" name="delete" value="Yes" class="btn btn-danger"/>
			<input type="submit" name="delete" value="Cancel" class="btn btn-success"/>
		</form>
	</div>

</div>
