<div class="mj3_tables clearfix">

	<?php echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML . ' &nbsp; Manage Journey Communications'); ?>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-comms-admin/journeys"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
		<li role="presentation"><a href="<?php echo $this->url("front-comms-admin/journeys", array("action" => "edit", "id" => $this->journey_id)); ?>" title="Edit Journey Settings" data-toggle="tooltip"><?php echo ICON_MEDIUM_MODIFY_HTML; ?></a></li>
		<li role="presentation"><a href="<?php echo $this->url("front-comms-admin/journeys", array("action" => "delete", "id" => $this->journey_id)); ?>" title="Delete Journey" data-toggle="tooltip"><?php echo ICON_MEDIUM_DELETE_HTML; ?></a></li>
		<!-- <li role="presentation"><a href="<?php echo $this->url("front-comms-admin/journeys", array("action" => "journey-flow", "id" => $this->journey_id)); ?>" title="View Journey Flow" data-toggle="tooltip"><?php echo ICON_MEDIUM_LINE_CHART_HTML; ?></a></li>-->
		<?php if ($this->objJourney->isExpired() === FALSE) :?>
			<!-- <li role="presentation"><a href="<?php //echo $this->url("front-comms-bulksend", array("action" => "set-criteria", "id" => $this->journey_id)); ?>" title="Send a Bulk Journey" data-toggle="tooltip"><?php echo ICON_MEDIUM_BULK_HTML; ?></a></li>-->
		<?php endif;?>
		<li class="mj3_btnchangeform"><a class="btn btn-success" href="<?php echo $this->url("front-comms-admin/comms", array("journey_id" => $this->journey_id, "action" => "create")); ?>"  title="Create Communication for Journey" data-toggle="tooltip"><?php echo ICON_MEDIUM_ADD_HTML . "Add Communication"; ?></a></li>
	</ul>

	<div class="mj3_table_contain clearfix">

		<?php

			//create comm type map
			$arr_comm_types = array(
					1 => "email",
					2 => "sms",
					3 => "fax",
			);

			//temporary container for comm number checks
			$arr_comm_numbers = array();

			//load service manager
			$sm = \FrontCore\Factories\FrontCoreServiceProviderFactory::getInstance();

		/**
		 * Prepare the data
		 */
		foreach ($this->objComms as $key => $objCommData) {

			if (!isset($objCommData->id)) {
				continue;
			} //end if

			//create entity
			$objCommAdmin = $sm->get("FrontCommsAdmin\Entities\FrontCommAdminEntity");
			$objCommAdmin->set($objCommData);

			//loop trough the table fields
			$arr_data["content"] 		= $objCommAdmin->content;
			$arr_data["description"] 	= $objCommAdmin->description;
			$arr_data["subject"] 		= $objCommAdmin->subject;
			$arr_data["behaviour"] 		= $objCommAdmin->journey_id;

			//format date
			$arr_date = explode("-", $objCommAdmin->date_expiry);
			if ($arr_date[0] != "0000")
			{
				$arr_data["expiry date"] = $objCommAdmin->date_expiry;
			} else {
				$arr_data["expiry date"] = "&nbsp;";
			}//end if

			$arr_data["priority"] 		= $objCommAdmin->priority;
			$arr_data["type"] 			= $arr_comm_types[$objCommAdmin->comm_via_id];
			$arr_data["delay"]			= $objCommAdmin->send_time;
			$arr_data["send_after"]		= $objCommAdmin->send_after;

			//simple check on communication numbers
			if (!in_array($objCommAdmin->comm_num, $arr_comm_numbers))
			{
				$arr_data["comm_num"] = $objCommAdmin->comm_num;
				$arr_comm_numbers[] = $objCommAdmin->comm_num;
				$prevent_active = FALSE;
			} else {
				$arr_data["comm_num"] = "<span class=\"label label-danger\" title=\"This communication number is used more than once\" data-toggle=\"tooltip\">" . $objCommAdmin->comm_num . "</span>";
				$prevent_active = TRUE;
			}//end if


 			if ($objCommAdmin->active == 1) {
				$arr_data["activate_commadmin"] = "<a href=\"" . $this->url("front-comms-admin/comms", array("action" => "status", "id" => $objCommAdmin->id, "journey_id" => $this->journey_id)) . "\"><span title=\"This Communication is active\" data-toggle=\"tooltip\">" . ICON_SMALL_ACTIVE_HTML . "</span></a>" . "</td>";
			} else {
				if (isset($prevent_active) && $prevent_active === TRUE)
				{
					$arr_data["activate_commadmin"] = "<span title=\"This Communication cannot be activated. Its communication number conflicts with that of another communication in this journey\" data-toggle=\"tooltip\">" . ICON_SMALL_INACTIVE_HTML . "</span>" . "</td>";
				} else {
					$arr_data["activate_commadmin"] = "<a href=\"" . $this->url("front-comms-admin/comms", array("action" => "status", "id" => $objCommAdmin->id, "journey_id" => $this->journey_id)) . "\"><span title=\"This Communication is not active\" data-toggle=\"tooltip\">" . ICON_SMALL_INACTIVE_HTML . "</span></a>" . "</td>";
				}//end if
			} // end if

			//set attachments url
			if ($objCommAdmin->allow_attachments == 1) {
				$attachments_url = "<a href=\"" . $this->url("front-comms-admin/comms", array("action" => "attachments", "id" => $objCommAdmin->id, "journey_id" => $this->journey_id)) . "\" title=\"Set Attachments\" data-toggle=\"tooltip\">" . ICON_SMALL_ATTACHMENT_HTML . "</a>";
			} else {
				$attachments_url = "";
			} //end if
$attachments_url = ""; //disabled for now because of sending structure...
			//do not allow updating where communication is active
			if ($objCommAdmin->active == 1)
			{
				$edit_url = "<a href=\"#\" title=\"Communication is active and cannot be updated\" data-toggle=\"tooltip\">" . ICON_SMALL_MODIFY_HTML . "</a>";
				$delete_commadmin = "<a href=\"#\" title=\"Communication is active and cannot be removed\" data-toggle=\"tooltip\">" . ICON_SMALL_DELETE_HTML . "</a>";
			} else {
				$edit_url = "<a href=\"" . $this->url("front-comms-admin/comms", array("action" => "edit", "id" => $objCommAdmin->id, "journey_id" => $this->journey_id)) . "\" title=\"Edit this Communication\" data-toggle=\"tooltip\">" . ICON_SMALL_MODIFY_HTML . "</a>";
				$delete_commadmin		= "<a href=\"" . $this->url("front-comms-admin/comms", array("action" => "delete", "id" => $objCommAdmin->id, "journey_id" => $this->journey_id)) . "\" title=\"Delete Communication\" data-toggle=\"tooltip\"" . ICON_SMALL_DELETE_HTML . "</a>";
			}//end if

			$preview_url			= "<a href=\"" . $this->url("majestic-external-view-comms") . "?cid=" . $objCommAdmin->id_encoded . "\" target=\"_blank\" title=\"Preview Communication\" data-toggle=\"tooltip\" >" . ICON_SMALL_SEARCH_HTML . "</a>";

			if ($objCommAdmin->comm_via_data_behaviour == "__email")
			{
				$embedded_images_url	= "<a href=\"" . $this->url("front-comms-admin/comm-embedded-images", array("journey_id" => $objCommAdmin->journey_id, "comm_id" => $objCommAdmin->id)) . "\" title=\"Embedded Images\" data-toggle=\"tooltip\" >" . ICON_SMALL_SAVE_HTML . "</a>";
			} else {
				$embedded_images_url	= "";
			}//end if

			//@TODO confirm embedded images - Scott
			//$arr_data["url"]		= $edit_url . $attachments_url . "&nbsp;" . $embedded_images_url . "&nbsp" . $preview_url . "&nbsp;" . $delete_commadmin;
			$arr_data["url"]		= $edit_url . $attachments_url . "&nbsp" . $preview_url . "&nbsp;" . $delete_commadmin;

			$arr[] = $arr_data;
		}//end foreach

		//create the add CommsAdmin
		$add_commadmin = "<a href=\"" . $this->url("front-comms-admin/comms", array("action" => "create", "journey_id" => $this->journey_id)) . "\" title=\"Create Communication\">" . ICON_MEDIUM_ADD_HTML . "</a>";

		if (is_array($arr))
		{
			echo "<div>";
			$i = 1;
			//loop through the comms
			echo "<div class=\"journey-comm-details\">";
			echo 	"<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
			foreach ($arr as $arr_comm) {
				echo 		"<tr>";
				echo 			"<th>Delay:</th>";
				echo 			"<th>";

				//set delay
				if (!is_numeric($arr_comm["delay"]) || $arr_comm["delay"] == "0")
				{
					echo "No Delay";
				} else {
					//calc days
					$days = floor(($arr_comm["delay"] / 86400));
					$arr_comm["delay"] = $arr_comm["delay"] - ($days * 86400);

					if ($arr_comm["delay"] <= 0)
					{
						$hours = 0;
						$minutes = 0;
					} else {
						//calc hours
						$hours = floor($arr_comm["delay"] / 3600);
						$arr_comm["delay"] = $arr_comm["delay"] - ($hours * 3600);

						//calc minutes
						if ($arr_comm["delay"] > 0)
						{
							$minutes = floor($arr_comm["delay"] / 60);
						} else {
							$minutes = 0;
						}//end if
					}//end if

					echo "$days Days, $hours Hours, $minutes Minutes";
				}//end if

				//set after value
				if ($arr_comm["send_after"] == 0)
				{
					echo " after Journey starts";
				} else {
					echo " after communication " . $arr_comm["send_after"];
				}//end if

				echo 			"</th>";
				echo 		"</tr>";
				echo 		"<tr>";
				echo 			"<th>Communication $i</th>";
				echo 			"<th class=\"commicons\" style=\"cursor: default;\">";
				echo 				$arr_comm["activate_commadmin"] . "&nbsp;" . $arr_comm["url"];
				echo 			"</th>";
				echo 		"</tr>";
				echo 		"<tr>";
				echo 			"<td>";
				echo 				"<span class=\"journey-comm-details-type\">Type: " . $arr_comm["type"] . "</span>";
				echo 			"</td>";
				echo 			"<td>";
				echo 				"<span class=\"journey-comm-details-description\">" . $arr_comm["description"] . "</span>";
				echo 			"</td>";
				echo 		"</tr>";
				echo		"<tr>";
				echo 			"<td>Expiry Date</td>";
				echo 			"<td><span class=\"journey-comm-details-expiry-date\">" . $arr_comm["expiry date"] . "</span></td>";
				echo 		"</tr>";
				echo		"<tr>";
				echo 			"<td>Subject</td>";
				echo 			"<td><span class=\"journey-comm-details-subject\">" . $arr_comm["subject"] . "</span></td>";
				echo 		"</tr>";
				echo		"<tr>";
				echo 			"<td>Number</td>";
				echo 			"<td><span class=\"journey-comm-details-number\">" . $arr_comm["comm_num"] . "</span></td>";
				echo 		"</tr>";
				echo 		"<tr><td colspan=\"2\" class=\"commspace\"></td></tr>";

				//increment counter
				$i++;
			}//end foreach
			echo 	"</table>";
			echo "</div>";
			echo "</div>";

		} else {
			echo "<div>";
			echo 	"<div class=\"journey-comm-details\">";
			echo 		"There are no communications available for this Journey";
			echo 	"</div>";
			echo "</div>";

		} //end if

		?>

	</div>

</div>
