<div class="mj3_tables clearfix">
<?php
echo $this->renderStandardViewHeader(ICON_LARGE_USER_HTML. '&nbsp; Create User Role Using Standard Role');
?>

	<ul class="nav nav-tabs">
		<li role="presentation">
			<?php echo "<a href=\"" . $this->url("front-users-roles/admin", array("action" => "get-standard-roles")) . "\" title=\"Back\" data-toggle=\"tooltip\">" . ICON_MEDIUM_BACK_HTML . "</a>";?>		
		</li>
	</ul>
	<div class="mj3_forms clearfix">
	<?php 
		$form = $this->form;
		$form->prepare();
		echo $this->renderSystemFormHelper($form, $this);
	?>
	</div>
</div>
