<?php
echo $this->doctype();
?>
<html>
	<?php
	echo $this->partial('layout/forms/header');
	?>
		<script type="text/javascript">
			//define some global javascript vars
			var global_wait_image = "<img src=\"<?php echo $this->layout()->cdn_url;?>/images/m3frontend/animations/please_wait.gif\" />";
			var cdn_url = '<?php echo $this->layout()->cdn_url; ?>';
		</script>
		<script src="/js/angular/helpers/helper.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-route.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-resource.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-cookies.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-sanitize.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/angular-animate.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/bootstrap/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/smart-table/smart-table.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/api-check/api-check.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/formly/formly.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/formly/angular-formly-templates-bootstrap/angular-formly-templates-bootstrap.min.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/promise-tracker/promise-tracker.js"></script>
		<script src="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/paginator/dirPagination.js"></script>

		<link rel="stylesheet" href="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/angular-motion/angular-motion.min.css">
		<link rel="stylesheet" href="<?php echo $this->layout()->cdn_url; ?>/js/vendor/angular/plugins/angular-motion/modules/collapse.min.css">

	<body>
		<div class="wrapper">
			<!-- Main content -->
			<div class="col-md-9 m3-content-section-main" role="main">
				<div class="bs-docs-section">
					<!-- External content -->
					<?php echo $this->content; ?>

					<?php
					if ($_GET["debug_display_errors"] == 1)
					{
						echo $this->partial("layout/api-data");
					}//end if
					?>
				</div>
			</div>
		</div>
	</body>
</html>





