<?php
echo $this->doctype();
?>
<html>
	<?php 
	echo $this->partial('layout/forms/header');
	?>
	<body>
		<div class="wrapper">
			<!-- Main content -->
			<div class="col-md-9 m3-content-section-main" role="main">
				<div class="bs-docs-section">
					<!-- notifications -->
					<?php echo $this->partial("layout/flash-messages");?>
					<!-- External content -->
					<?php echo $this->content; ?>
					
					<?php
					if ($_GET["debug_display_errors"] == 1)
					{
						echo $this->partial("layout/api-data");
					}//end if
					?>
				</div>
			</div>
		</div>
	</body>
</html>





