<div class="mj3_tables clearfix">

<?php echo $this->renderStandardViewHeader(ICON_LARGE_SETTINGS_HTML .'&nbsp; Set Available Reports'); ?>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-report-config"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>

	<div class="mj3_forms clearfix">
		<h4>Define Reports that should be visible to users</h4>
		<?php
			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this);
		?>

	</div><!-- mj3_forms clearfix -->

</div>
