<div class="mj3_tables clearfix">

<?php echo $this->renderStandardViewHeader(ICON_LARGE_SETTINGS_HTML .'&nbsp; Report Options'); ?>

	<div class="mj3_table_contain clearfix">
		<div class="">
			<a href="<?php echo $this->url('front-report-config', array('action' => 'configure-reports-available'))?>" title="Set available reports"><span class="glyphicon glyphicon-th-list"></span> Set which reports should be available</a>
		</div>
	</div>

</div>
