<script type="text/javascript">
	jQuery(document).ready(function () {
		//create new tab to load webform for contact
		jQuery("#form-contact-manual").change(function () {
			if (jQuery(this).val() == '')
			{
				return true;
			}//end if

			var form_url = '<?php echo $form_url = "/forms/bf/00001/" . $this->contact_id?>';
			window.open(form_url.replace('00001', jQuery(this).val()), '_blank');
		});
	});
</script>

<div class="form-group form-element-fname has-feedback">
	<label for="form-contact-manual" class="control-label">Complete Form</label>
	<select class="form-control" id="form-contact-manual">
		<option value="">--select--</option>
		<?php
			foreach ($this->objWebForms as $objForm)
			{
				if (!isset($objForm->id) || !is_numeric($objForm->id))
				{
					continue;
				}//end if

				if ($objForm->form_types_behaviour == '__web')
				{
					echo '<option value="' . $objForm->id . '">' . $objForm->form . "</option>";
				}//end if
			}//end foreach
		?>
	</select>
</div>
<?php
echo "<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
echo 	"<tr>";
echo 		"<th>Date</th>";
echo 		"<th>Type</th>";
echo 		"<th>Form</th>";
echo 		"<th>User</th>";
echo 	"</tr>";

foreach ($this->objContactForms as $objForm)
{
	if (!is_object($objForm) || !method_exists($objForm, 'get') || !is_numeric($objForm->get("id")))
	{
		continue;
	}//end if

	//set form url
	switch (strtolower($objForm->get("form_behaviour")))
	{
		case "__web":
			$form_url = "<a href=\"/forms/bf/" . $objForm->get("form_id") . "/" . $objForm->get("reg_id_encoded") . "\" title=\"View web form\" target=\"_blank\" data-toggle=\"tooltip\">" . $objForm->get("form") . "</a>";
			break;

		case "__viral":
			$form_url = "<a href=\"/forms/vbf/" . $objForm->get("form_id") . "/" . $objForm->get("reg_id_encoded") . "\" title=\"View viral form\" target=\"_blank\" data-toggle=\"tooltip\">" . $objForm->get("form") . "</a>";
			break;

		case "__cpp":
			$form_url = $objForm->get('form');
			break;

		default:
			continue(2);
			break;
	}//end switch

	//set date
	$date = $this->renderFormatUserDate(array("date" =>  $objForm->get("tstamp"), "options" => array(
			"output_format" => "d M Y H:i",
	)));

	echo "<tr>";
	echo 	"<td>" . $date . "</td>";
	echo 	"<td>" . $objForm->get("form_behaviour_label") . "</td>";
	echo 	"<td>" . $form_url . "</td>";
	echo 	"<td>" . $objForm->get("uname") . "</td>";
	echo "</tr>";
}//end foreach

echo "</table>";