<button id="change-contact-status-link" class="btn btn-primary" title="Change Contact Status" data-toggle="tooltip">Change Status</button><br>

<script type="text/javascript">
	jQuery(document).ready(function() {
		var parent_element;

		//monitor the update contact status link
		jQuery("#change-contact-status-link").click(function (e) {
			e.preventDefault();

			//get parent section for later use
			parent_element = jQuery(this).parent();

			//load the dialog
			jQuery("#update-contact-status-form").modal();
			return false;
		});

		//monitor save button
		jQuery("#save-contact-status").click(function (e) {
			e.preventDefault();

			jQuery.ajax({
				url : "<?php echo $this->url("front-contact-toolkit", array("action" => "contact-status-history", "id" => $this->contact_id));?>",
				type : "POST",
				data : {
					comment : jQuery("#status-comment").val(),
					status : jQuery("#status").val(),
					behaviour : "user"
				}
			})
			.done (function (result) {
				if (result != "true")
				{
					alert(result);
					return false;
				}//end if

				location.reload();
			});

			//close the dialog
			jQuery("#update-contact-status-form").modal('toggle');
		});
	});
</script>
<?php
//set arry with behaviour descriptions
$arr_descriptions = array(
	"__system" => "System",
	"__form" => "Form",
	"__user" => "User",
);

echo "<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
echo 	"<tr>";
echo 		"<th>Date</th>";
echo 		"<th>Status</th>";
echo 		"<th>&nbsp;</th>";
echo 		"<th>User</th>";
echo 	"</tr>";

foreach ($this->objContactStatusData as $objStatus)
{
	if (!method_exists($objStatus, 'get') || !is_numeric($objStatus->get("id")))
	{
		continue;
	}//end if

	//set date
	$date = $this->renderFormatUserDate(array("date" =>  $objStatus->get("tstamp"), "options" => array(
			"output_format" => "d M Y H:i",
	)));
	
	echo "<tr>";
	echo 	"<td>" . $date . "</td>";
	echo	"<td><span style=\"color: " . $objStatus->get("registration_status_colour") . "\">" . $objStatus->get("registration_status_status") . "</span></td>";
	echo 	"<td>" . $arr_descriptions[$objStatus->get("behaviour")] . "</td>";
	if ($objStatus->get("users_uname") != "")
	{
		echo "<td>" . $objStatus->get("users_uname") . "</td>";
	} else {
		echo "<td>&nbsp;</td>";
	}//end if

	echo "</tr>";

}//end foreach

echo "</table>";

?>

<div id="update-contact-status-form" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
 				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title">Contact Status</h4>
			</div>
			<div class="modal-body">
				<form action="#">
					<label for="status">Contact Status</label>
					<select name="status" id="status">
						<option value="">--select--</option>
						<?php foreach ($this->objStatuses as $objStatus)
						{
							if ($objStatus->status == "")
							{
								continue;
							}//end if
							echo "<option value=\"" . $objStatus->id . "\">" . $objStatus->status . "</option>";
						}//end foreach?>
					</select>
					<br />

					<label for="status-comment">Comment</label>
					<textarea id="status-comment"></textarea>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal" id="save-contact-status">Save</button>
        		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        	</div>
		</div>
	</div>
</div>
