<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader('&nbsp; Embedded Images - Remove Image'); ?>

	<div class="mj3_forms clearfix">
		<form method="post">
			<h3>Are you sure you want to remove the embedded image?</h3>
			<input type="submit" name="delete" value="Yes" class="btn btn-danger"/>
			<input type="submit" value="Cancel" class="btn btn-success"/>
		</form>
	</div>
</div>


