<div class="mj3_tables clearfix">
<?php
	echo $this->renderStandardViewHeader(ICON_LARGE_USER_DATA_ACL_HTML . ' &nbsp; User Data Access Rules for ' . $this->objUser->uname);
?>
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-users"); ?>" data-toggle="tooltip" title="Back"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
		<li role="presentation"><a href="<?php echo $this->url("front-users-roles/user", array("action" => "list-user-roles", 'user_id' => $this->objUser->id)); ?>" data-toggle="tooltip" title="Manage User Roles"><?php echo  ICON_MEDIUM_ROLES_HTML; ?></a></li>
	</ul>
	<div class="mj3_forms clearfix">
		<?php
		$form = $this->form;
		$form->prepare();
		echo $this->renderSystemFormHelper($form, $this);
		?>
	</div>
</div>