<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_ANNOUNCEMENT_HTML .'&nbsp; Create Announcement'); ?>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-power-tools/announcements"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>

	<div class="mj3_forms clearfix">

		<?php

		$form = $this->form;
		//$form->setAttribute("class", "form system-form form-e-link");
		//$form->setAttribute("action", "<a href=\"" . $this->url("front-power-tools/announcements", array("action" => "create")));
		$form->prepare();
		echo $this->renderSystemFormHelper($form, $this);
		?>

	</div>

</div>