<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_ANNOUNCEMENT_HTML .'&nbsp; Announcements'); ?>

<ul class="nav nav-tabs">
		<li class="mj3_btnchangeform"><a href="<?php echo $this->url("front-power-tools/announcements", array("action" => "create")); ?>" title="" data-toggle="tooltip" class="btn btn-success" data-original-title="Create Announcement"><?php echo ICON_LARGE_ADD_HTML. 'Create Announcement'; ?></a></li>
	</ul>


	<div class="mj3_table_contain clearfix">

		<?php

		/**
		 * prepare the data.
		 */
		foreach ($this->objAnnouncements as $key => $objAnnouncement) {

			if (!isset($objAnnouncement->id)) {
				continue;
			} //end if

			$arr_data["powertool"] = $objAnnouncement->announcement;
			$arr_data["created"] = $objAnnouncement->date_created;
			$arr_data["site"] = $objAnnouncement->fk_site_id;

			if  ($objAnnouncement->active == 1) {
				$arr_data["active_announcement"] = "<a href=\"" . $this->url("front-power-tools/announcements", array("action" => "status", "id" => $objAnnouncement->id)) . "\" title=\"Deactivate Announcement\" class=\"page-e-link\">" . ICON_SMALL_ACTIVE_HTML . "</a>" . "</td>";
			} else {
				$arr_data["active_announcement"] = "<a href=\"" . $this->url("front-power-tools/announcements", array("action" => "status", "id" => $objAnnouncement->id)) . "\" title=\"Activate Announcement\" class=\"page-e-link\">" . ICON_SMALL_INACTIVE_HTML . "</a>" . "</td>";
			} //end if

			$edit_url = "<a href=\"" . $this->url("front-power-tools/announcements", array("action" => "edit", "id" => $objAnnouncement->id)) . "\" title=\"Edit Announcement\" class=\"page-e-link\">" . ICON_SMALL_MODIFY_HTML . "</a>";
			$delete_url = "<a href=\"" . $this->url("front-power-tools/announcements", array("action" => "delete", "id" => $objAnnouncement->id)) . "\" title=\"Delete Announcement\" class=\"page-e-link\">" . ICON_SMALL_DELETE_HTML . "</a>";
			$arr_data["url"] = $edit_url . "&nbsp;" . $delete_url;

			$arr[] = $arr_data;
		} //end foreach

		//create add url
		$add_announcement = "";
		$css_id = str_replace(".", "", microtime(TRUE));
		echo $this->renderDataTableHelper(array("return_script" => TRUE), $css_id);
		echo $this->renderSimpleHTMLTable($arr, array("Announcement", "Date", "Site", "Active", $add_announcement), array("id" => $css_id));
		?>

	</div>

</div>