<div class="mj3_forms clearfix">

<?php

	echo $this->renderStandardViewHeader(ICON_LARGE_CONTACTS_HTML . ' &nbsp; Edit Contact Details');
	?>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-contacts"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
		<li role="presentation"><a href="<?php echo $this->url("front-contacts", array("id" => $this->objContact->get("id"), "action" => "view-contact")); ?>" title="View Contact" data-toggle="tooltip"><?php echo ICON_MEDIUM_PROFILE_HTML; ?></a></li>
		<li role="presentation"><a href="#" <?php echo $this->objContact->get("id"); ?> class="contact_comms" data-contact-id="<?php echo $this->objContact->get("id"); ?>" title="Send a Journey" data-toggle="tooltip"><?php echo ICON_MEDIUM_COMMS_HTML; ?></a></li>
		<li class="mj3_btnchangeform"><a class="btn btn-success" href="<?php echo $this->url("front-contacts", array("action" => "select-profile-form")); ?>?redirect=<?php echo $this->url("front-contacts", array("action" => "edit-contact", "id" => $this->objContact->get("reg_id"))); ?>" title="Change layout" data-toggle="tooltip"><?php echo ICON_MEDIUM_LAYOUT_HTML . "&nbsp; Change layout";?> </a></li>
	</ul>
	<div class="mj3_tables clearfix">
		<?php
			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this);
		?>
	</div><!-- tables div close -->
</div><!-- forms div close -->