<!-- Load bulk send javascript file -->
<script type="text/javascript" src="/js/bulksend/general.js"></script>

<?php

//insert ajax urls
echo "<script type=\"text/javascript\">";
echo 	"var ajax_reg_status_list 			= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-contact-status-list")) . "\";";
echo 	"var ajax_web_forms_url 			= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-web-forms-list")) . "\";";
echo 	"var ajax_web_form_fields_url 		= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-web-form-fields-list")) . "\";";
echo 	"var ajax_sales_funnels_url 		= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-sales-funnels-list")) . "\";";
echo 	"var ajax_standard_fields_list_url 	= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-standard-fields-list")) . "\";";
echo 	"var ajax_standard_field_data_url 	= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-standard-field-criteria")) . "\";";
echo 	"var ajax_custom_fields_list_url 	= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-custom-fields-list")) . "\";";
echo 	"var ajax_custom_field_data_url 	= \"" . $this->url("front-comms-bulksend", array("action" => "ajax-custom-field-criteria")) . "\";";

echo 	 "jQuery(document).ready(function () {
			//monitor the delete request button
			jQuery(\"#delete_request\").click(function () {
				if (!confirm(\"Are you sure you want to delete this Bulk Send Request? This cannot be undone.\"))
				{
					return false;
				}//end if
			});
		 });";
echo "</script>";

//display journey data
echo "<div class=\"mj3_tables clearfix\">";
echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML . '&nbsp;Journey Details:&nbsp;<a href="' . $this->url("front-comms-admin/journeys", array("id" => $this->objJourney->get("id"), "action" => "edit")) . '">' . $this->objJourney->get("journey") . '</a> ');



echo "<ul class=\"nav nav-tabs\">";
echo "<li role=\"presentation\">";
echo "<a href=\"" . $this->url("front-comms-bulksend-admin") . "\" title=\"Back\" data-toggle=\"tooltip\">" . ICON_MEDIUM_BACK_HTML . "</a>";
echo "</li></ul>";

echo "<div class=\"mj3_table_contain clearfix\">";

//echo 	"<h3 class=\"\" data-uk-toggle=\"{target: '#journey-details-summary', animation:'uk-animation-slide-left, uk-animation-slide-bottom'}\">Journey Details: <a href=\"" . $this->url("front-comms-admin/journeys", array("id" => $this->objJourney->get("id"), "action" => "edit")) . "\" title=\"Edit Journey\">" . $this->objJourney->get("journey") . "</a></h3>";
echo 	"<div id=\"journey-details-summary\">";
echo 		"<h4>Desription : " . $this->objJourney->get("description") . "</h4>";
if ($this->objJourney->isExpired() === TRUE)
{
	echo 		"<p style=\"padding: 7px;\" class=\"text-danger bg-danger\">Warning: This journey has expired</p>";
}//end if
echo 		"<h4>Communications</h4>";
echo 		"<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
echo 			"<tr>";
echo 				"<th>Number</th>";
echo 				"<th>Type</th>";
echo 				"<th>Expires</th>";
echo 				"<th>Active</th>";
echo 				"<th>&nbsp;</th>";
echo 			"<tr>";

foreach ($this->objJourney->get("comms") as $objComm)
{
	echo	"<tr>";
	echo 		"<td>" . $objComm->comm_num . "</td>";
	echo 		"<td>" . $objComm->comm_via_data_comm_via . "</td>";
	echo 		"<td>" . $objComm->date_expiry . "</td>";

	if ($objComm->active == 1)
	{
		echo 	"<td>" . ICON_SMALL_ACTIVE_HTML . "</td>";
	} else {
		echo 	"<td>" . ICON_SMALL_ACTIVE_HTML . "</td>";
	}//end if

	echo 		"<td><a href=\"" . $this->url("front-comms-admin/comms", array("journey_id" => $this->objJourney->get("id"), "id" => $objComm->id, "action" => edit)) . "\" title=\"Edit Communication\" data-toggle=\"tooltip\">" . ICON_SMALL_MODIFY_HTML . "</a>";

	echo 	"</tr>";
}//end foreach
echo 	"</table>";
echo "</div></div>";

//extract params and group by type
$arr_params_general = array();
$arr_params_custom = array();
$arr_params_std = array();
$arr_params_forms = array();

foreach ($this->objBulkSendRequest->arr_params as $objParam)
{
	switch (strtolower($objParam->field_type))
	{
		case "general":
			switch ($objParam->field_name)
			{
				case "forms_completed.form_id":
				case "sales_funnel.fk_form_id":
					$arr_params_forms[] = $objParam;
					break;

				default:
					$arr_params_general[] = $objParam;
					break;
			}//end switch
			break;

		case "custom":
			$arr_params_custom[] = $objParam;
			break;

		case "std":
			$arr_params_std[] = $objParam;
			break;
	}//end switch
}//end foreach
?>
<div class="mj3_table_contain clearfix">
<?php
//display bulk send details
echo "<fieldset><h4>Request Details</h4>";
echo 	"<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
echo 		"<tr>";
echo 			"<td>Requested on</td>";
echo 			"<td>" . $this->objBulkSendRequest->datetime_created . "</td>";
echo 		"</tr>";
echo 		"<tr>";
echo 			"<td>Requested by</td>";
echo 			"<td>";

//load user data
$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_user_id);
echo 				$objUser->get("uname") . "&nbsp(" . $objUser->get("fname") . "&nbsp;" . $objUser->get("sname") . ")";
echo 			"</td>";
echo 		"</tr>";

//display approval status
echo 		"<tr>";
echo 			"<td>Approval Status</td>";
echo			"<td>";

//check if bulk comm has first level approval
if ($this->objBulkSendRequest->fk_cancelled_user_id > 0)
{
	echo "Cancelled";
} else {
	if ($this->objBulkSendRequest->fk_approved_user_id < 1)
	{
		echo "Requires user approval";
	} elseif ($this->objBulkSendRequest->fk_approved_user_id > 0 && $this->objBulkSendRequest->fk_approved_admin_user_id < 1) {
		echo "Requires Administrator Approval<br/>";
		//load user details
		$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_approved_user_id);
		echo "Approved by " . $objUser->get("uname") . " (" . $objUser->get("fname") . " " . $objUser->get("sname") . ") on " . $this->objBulkSendRequest->datetime_approved;
	} elseif ($this->objBulkSendRequest->fk_approved_user_id > 0 && $this->objBulkSendRequest->fk_approved_admin_user_id > 0) {
		echo "Approved<br/>";
		//load user details
		$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_approved_user_id);
		echo "Approved by " . $objUser->get("uname") . " (" . $objUser->get("fname") . " " . $objUser->get("sname") . ") on " . $this->objBulkSendRequest->datetime_approved . "<br/>";

		//load admin details
		$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_approved_admin_user_id);
		echo "Admin Approval by " . $objUser->get("uname") . " (" . $objUser->get("fname") . " " . $objUser->get("sname") . ") on " . $this->objBulkSendRequest->datetime_approved;
	}//end
}//end if

echo 			"</td>";
echo 		"</tr>";

//display request status
echo 		"<tr>";
echo 			"<td>Sending Status</td>";
echo 			"<td>";

if ($this->objBulkSendRequest->fk_cancelled_user_id > 0)
{
	echo "Cancelled";
} else {
	if ($this->objBulkSendRequest->datetime_started == "0000-00-00 00:00:00")
	{
		if ($this->objBulkSendRequest->fk_approved_user_id > 0 && $this->objBulkSendRequest->fk_approved_admin_user_id > 0)
		{
			echo "Waiting";
		} else {
			echo "Awaiting Approval";
		}//end if
	} elseif ($this->objBulkSendRequest->datetime_started != "0000-00-00 00:00:00" && $this->objBulkSendRequest->datetime_ended == "0000-00-00 00:00:00") {
		echo "In Progress";
	} elseif ($this->objBulkSendRequest->datetime_ended != "0000-00-00 00:00:00") {
		echo "Completed";
	}//end if
}//end if

echo 			"</td>";
echo 		"</tr>";

//display contacts selected
echo 		"<tr>";
echo 			"<td>Contact Allocated</td>";
echo 			"<td>" . (int) $this->objBulkSendRequest->num_allocated . "</td>";
echo 		"</tr>";
echo 	"</table>";
echo "</fieldset>";
?>
</div>
<div class="mj3_forms clearfix">
<?php

echo "<form id=\"bulk_send_criteria_review\" method=\"post\">";
echo "<fieldset><h4>Send Criteria</h4>";

if (count($arr_params_general) > 0)
{
	echo "<fieldset><h4>General</h4>";

	foreach ($arr_params_general as $objParam)
	{
		switch ($objParam->field_name)
		{
			case "registrations.reg_status_id":
				echo "<label for=\"status_operator\">Contact Status</label>";
				echo "<select name=\"status_operator\" id=\"status_operator\">";

				if ($objParam->field_value == "equals")
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"equals\" $selected>is equal to</option>";

				if ($objParam->field_value == "notequals")
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"notequals\" $selected>is not equal to</option>";
				echo "</select>";

				//load contact status data
				$objContactStatus = $this->model_contact_status->fetchContactStatus($objParam->field_value);

				echo "<select name=\"reg_status_id\" id=\"reg_status_id\">";
				echo 	"<option value=\"\">--select--</option>";
				echo 	"<option value=\"" . $objParam->field_value . "\" selected=\"selected\">" . $objContactStatus->get("status") . "</option>";
				echo 	"<option value=\"*load_data*\">Load Data</select>";
				echo "</select>";
				echo "<br/>";
				break;

			case "registrations.datetime_created":
				//extract dates from value
				$arr_dates = explode(" AND ", $objParam->field_value);
				echo "<label for=\"date_created_start\">Date Created</label>";
				echo "<input type=\"text\" name=\"date_created_start\" id=\"date_created_start\" class=\"datepicker\" readonly=\"readonly\" value=\"" . str_replace("'", "", str_replace(" ", "", $arr_dates[0])) . "\"/>&nbsp; -- &nbsp;";
				echo "<input type=\"text\" name=\"date_created_end\" id=\"date_created_end\" class=\"datepicker\" readonly=\"readonly\" value=\"" . str_replace("'", "", str_replace(" ", "", $arr_dates[1])) . "\"/>";
				echo "<br/>";
				break;

			case "registrations.email":
				echo "<label for=\"email_address\">E-mail address</label>";
				echo "<select name=\"email_address\" id=\"email_address\">";
				echo 	"<option value=\"\">--select--</option>";

				if ($objParam->field_value == 1)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"1\" $selected>Valid format</option>";

				if ($objParam->field_value == 2)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"2\" $selected>Not suspended</option>";

				if ($objParam->field_value == 3)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"3\" $selected>Valid format and not suspended</option>";

				if ($objParam->field_value == 4)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"4\" $selected>Invalid format or blank</option>";

				if ($objParam->field_value == 5)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"5\" $selected>Suspended</option>";

				if ($objParam->field_value == 6)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"6\" $selected>Invalid format or blank or suspended</option>";
				echo "</select>";
				echo "<br/>";
				break;

			case "registrations.cell":
				echo "<label for=\"sms_number\">SMS</label>";
				echo "<select name=\"sms_number\" id=\"sms_number\">";
				echo 	"<option value=\"\">--select--</option>";
				if ($objParam->field_value == 1)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"1\" $selected>Valid Format</option>";

				if ($objParam->field_value == 2)
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"2\" $selected>Invalid format or blank</option>";
				echo "</select>";
				break;
		}//end switch
	}//end foreach

	echo "</fieldset>";
}//end if - general fields

if (count($arr_params_forms) > 0)
{
	echo "<fieldset><h4>Forms</h4>";

	foreach ($arr_params_forms as $objParam)
	{
		switch (strtolower($objParam->field_name))
		{
			case "forms_completed.form_id":
				//insert javascript to display the web form drop selection
				echo "<script type=\"text/javascript\">
							jQuery(document).ready(function () {
								jQuery(\"#form_operator\").show();
							});
					  </script>";

				echo "<label for=\"form_id\">Web</label>";

				//load forms from model
				$objForms = $this->model_front_comms_bulk_send->fetchWebForms();
				echo "<select name=\"form_id\" id=\"form_id\">";
				echo 	"<option value=\"\">--select--</option>";
				foreach ($objForms as $objForm)
				{
					if ($objParam->field_value == $objForm->id)
					{
						$selected = "selected=\"selected\"";
					} else {
						$selected = "";
					}//end if
					echo "<option value=\"" . $objForm->id . "\" $selected>" . $objForm->form . "</option>";
				}//end foreach

				echo "</select>";
				echo "&nbsp;";
				echo "<select name=\"form_operator\" id=\"form_operator\">";
				echo 	"<option value=\"\">--select--</option>";

				if ($objParam->field_operator == "complete")
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"complete\" $selected>has been completed</option>";

				if ($objParam->field_operator == "uncomplete")
				{
					$selected = "selected=\"selected\"";
				} else {
					$selected = "";
				}//end if
				echo 	"<option value=\"uncomplete\" $selected>has not been completed</option>";
				echo "</select>";
				echo "<br/>";
				break;

			case "sales_funnel.fk_form_id":
				echo "<label for=\"sales_funnel_id\">Sales Funnel</label>";

				//load forms from model
				$objForms = $this->model_front_comms_bulk_send->fetchWebForms();
				echo "<select name=\"sales_funnel_id\" id=\"sales_funnel_id\">";
				echo "<option value=\"\">--select--</option>";

				foreach ($objForms as $objForm)
				{
					if ($objParam->field_value == $objForm->id)
					{
						$selected = "selected=\"selected\"";
					} else {
						$selected = "";
					}//end if

					echo "<option value=\"" . $objForm->id . "\" $selected>" . $objForm->form . "</option>";
				}//end foreach

				echo "</select>";
				break;
		}//end switch
	}//end foreach

	echo "</fieldset>";
}//end if

if (count($arr_params_custom) > 0 || count($arr_params_std) > 0)
{
	echo "<fieldset><h4>Fields</h4>";

	//standard fields
	if (count($arr_params_std) > 0)
	{
		echo "<fieldset><h4>Standard Fields</h4>";

		//load standard fields
		$arr_std_fields = $this->model_front_comms_bulk_send->fetchStandardFields();

		//create the standard field drop down
		echo 	"<table>";
		echo 		"<tr>";
		echo 			"<td valign=\"top\">";
		echo 				"<select id=\"standard_fields_list\">";
		echo 					"<option value=\"\">--select--</option>";

		foreach ($arr_std_fields as $objField)
		{
			echo 				"<option value=\"" . $objField->get("id") . "\">" . $objField->get("description") . "</option>";
		}//end foreach

		echo 				"</select>";
		echo 			"</td>";
		echo 			"<td>";
		echo 				"<div id=\"standard_fields_criteria\">";
		echo 					"<!-- container for standard field criteria -->";

		foreach ($arr_params_std as $objParam)
		{
			//load preformated html from model and helper
			echo $this->model_front_comms_bulk_send->fetchStandardField($objParam->fk_id_fields_std, $objParam->field_value, $objParam);
		}//end foreach

		echo 				"</div>";
		echo 			"</td>";
		echo 		"</tr>";
		echo 	"</table>";
		echo "</fieldset>";
	}//end if


	//custom fields
	if (count($arr_params_custom) > 0)
	{
		echo "<fieldset><h4>Custom Fields</h4>";

		//load custom fields
		$arr_custom_fields = $this->model_front_comms_bulk_send->fetchCustomFields();
		//create custom field drop down
		echo 	"<table>";
		echo 		"<tr>";
		echo 			"<td>";
		echo 				"<select id=\"\">";
		echo 					"<option value=\"\">--select--</option>";

		foreach ($arr_custom_fields as $objField)
		{
			echo 				"<option value=\"" . $objField->get("id") . "\">" . $objField->get("description") . "</option>";
		}//end foreach

		echo 				"</select>";
		echo 			"</td>";
		echo 			"<td>";
		echo 			"<div id=\"custom_fields_criteria\">";
		echo 				"<!-- container for standard field criteria -->";

		foreach ($arr_params_custom as $objParam)
		{
			echo $this->model_front_comms_bulk_send->fetchCustomField($objParam->fk_id_fields_custom, $objParam->field_value, $objParam);
		}//end foreach

		echo 			"</div>";
		echo 			"</td>";
		echo 		"</tr>";
		echo 	"</table>";
		echo "</fieldset>";
	}//end if

	echo "</legend>";
}//end if - fields fieldset

echo "</fieldset>";

echo "<fieldset><h4>Options</h4>";

echo 	"<span class=\"bulk_send_options\">Begin with &nbsp;</span>";

if ($this->objBulkSendRequest->get("allocate_new") == "0")
{
	$checked = "checked=\"checked\"";
} else {
	$checked = "";
}//end if
echo 	"<input type=\"radio\" name=\"allocate_new\" id=\"allocate_new\" value=\"0\"/ $checked>&nbsp;Oldest&nbsp;";

if ($this->objBulkSendRequest->get("allocate_new") == "1")
{
	$checked = "checked=\"checked\"";
} else {
	$checked = "";
}//end if
echo 	"<input type=\"radio\" name=\"allocate_new\" id=\"allocate_new\" value=\"1\"/ $checked>&nbsp;Newest";
echo 	"<br/>";

echo 	"<span class=\"bulk_send_options\">Start All &nbsp;</span>";

if ($this->objBulkSendRequest->get("allocate_all") == "1" && $this->objBulkSendRequest->get("allocate_num") == "")
{
	$checked = "checked=\"checked\"";
} else {
	$checked = "";
}//end if

if (is_numeric($this->objBulkSendRequest->get("allocate_num")))
{
	$allocate_num_value = $this->objBulkSendRequest->get("allocate_num");
} else {
	$allocate_num_value = "";
}//end if

echo 	"<input type=\"checkbox\" name=\"allocate_all\" id=\"allocate_all\" value=\"1\" $checked/>&nbsp;<span style=\"\">OR</span>&nbsp;";
echo 	"<input type=\"text\" name=\"allocate_num\" id=\"allocate_num\" value=\"$allocate_num_value\"/ style=\"width: 100px;\">&nbsp;of <span style=\"font-weight: bold;\">" . $this->objBulkSendRequest->get("send_total") . "</span>&nbsp;Contacts";
echo 	"<br/>";

// echo 	"<span class=\"bulk_send_options\">I agree to the terms and conditions</span>&nbsp;";
// echo 	"<input type=\"checkbox\" name=\"terms\" id=\"terms\" value=\"1\"/>";
echo "</fieldset><br/>";

//only display approval and update where first level approval has not taken place yet
if ($this->objBulkSendRequest->get("fk_approved_user_id") == "0" || $this->objBulkSendRequest->get("fk_approved_user_id") == "")
{
	echo "<input type=\"submit\" class=\"btn btn-primary\" value=\"Update\" name=\"submit_update\"/>&nbsp;";
	echo "<input type=\"submit\" value=\"Request Approval\" class=\"btn btn-success\" name=\"request_approval\"/>&nbsp;";
} elseif (is_numeric($this->objBulkSendRequest->get("fk_approved_user_id")) && $this->objBulkSendRequest->get("fk_approved_user_id") != "0" && ($this->objBulkSendRequest->get("fk_approved_admin_user_id") == "0" || $this->objBulkSendRequest->get("fk_approved_admin_user_id") == "")) {
	//display cancel option only where approval has been requested
	echo "<input type=\"submit\" value=\"Cancel Approval\" class=\"btn btn-danger\" name=\"cancel_approval\"/>&nbsp;";
}//end if

//only display delete option where request is not fully approved, and sending has not been completed
if ($this->objBulkSendRequest->get("fk_approved_admin_user_id") > 0 && $this->objBulkSendRequest->get("datetime_ended") != "0000-00-00 00:00:00")
{
	//sending completed
	echo "<input type=\"submit\" value=\"Delete Request\" class=\"btn btn-danger\" name=\"delete_request\" id=\"delete_request\"/>";
} elseif ($this->objBulkSendRequest->get("fk_approved_admin_user_id") < 1) {
	//not approved yet
	echo "<input type=\"submit\" value=\"Delete Request\" class=\"btn btn-danger\" name=\"delete_request\" id=\"delete_request\"/>";
} //end if
echo "</form>";

echo "</div></div>";//mj3_tables closing div and mj3_forms closing div