<!-- Load bulk send javascript file -->
<script type="text/javascript" src="/js/bulksend/general.js"></script>

<?php
//display journey data
echo "<div class=\"mj3_tables clearfix\">";
echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML . '&nbsp;Journey Details:&nbsp;<a href="' . $this->url("front-comms-admin/journeys", array("id" => $this->objJourney->get("id"), "action" => "edit")) . '">' . $this->objJourney->get("journey") . '</a> ');

echo "<ul class=\"nav nav-tabs\">";
echo "<li role=\"presentation\">";
echo "<a href=\"" . $this->url("front-comms-bulksend-admin") . "\" title=\"Back\" data-toggle=\"tooltip\">" . ICON_MEDIUM_BACK_HTML . "</a>";
echo "</li></ul>";

echo "<div class=\"mj3_table_contain clearfix\">";

//echo 	"<h3 class=\"\" data-uk-toggle=\"{target: '#journey-details-summary', animation:'uk-animation-slide-left, uk-animation-slide-bottom'}\">Journey Details: <a href=\"" . $this->url("front-comms-admin/journeys", array("id" => $this->objJourney->get("id"), "action" => "edit")) . "\" title=\"Edit Journey\">" . $this->objJourney->get("journey") . "</a></h3>";
echo 	"<div id=\"journey-details-summary\">";
echo 		"<h4>Desription : " . $this->objJourney->get("description") . "</h4>";
if ($this->objJourney->isExpired() === TRUE)
{
	echo 		"<p style=\"padding: 7px;\" class=\"text-danger bg-danger\">Warning: This journey has expired</p>";
}//end if
echo 		"<h4>Communications</h4>";
echo 		"<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
echo 			"<tr>";
echo 				"<th>Number</th>";
echo 				"<th>Type</th>";
echo 				"<th>Expires</th>";
echo 				"<th>Active</th>";
echo 				"<th>&nbsp;</th>";
echo 			"<tr>";

foreach ($this->objJourney->get("comms") as $objComm)
{
	echo	"<tr>";
	echo 		"<td>" . $objComm->comm_num . "</td>";
	echo 		"<td>" . $objComm->comm_via_data_comm_via . "</td>";
	echo 		"<td>" . $objComm->date_expiry . "</td>";

	if ($objComm->active == 1)
	{
		echo 	"<td>" . ICON_SMALL_ACTIVE_HTML . "</td>";
	} else {
		echo 	"<td>" . ICON_SMALL_ACTIVE_HTML . "</td>";
	}//end if

	echo 		"<td><a href=\"" . $this->url("front-comms-admin/comms", array("journey_id" => $this->objJourney->get("id"), "id" => $objComm->id, "action" => edit)) . "\" title=\"Edit Communication\" data-toggle=\"tooltip\">" . ICON_SMALL_MODIFY_HTML . "</a>";

	echo 	"</tr>";
}//end foreach
echo 	"</table>";
echo "</div></div>";
?>
<div class="mj3_table_contain clearfix">
<?php
//display bulk send details
echo "<fieldset><h4>Request Details</h4>";
echo 	"<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
echo 		"<tr>";
echo 			"<td>Requested on</td>";
echo 			"<td>" . $this->objBulkSendRequest->datetime_created . "</td>";
echo 		"</tr>";
echo 		"<tr>";
echo 			"<td>Requested by</td>";
echo 			"<td>";

//load user data
$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_user_id);
echo 				$objUser->get("uname") . "&nbsp(" . $objUser->get("fname") . "&nbsp;" . $objUser->get("sname") . ")";
echo 			"</td>";
echo 		"</tr>";

//display approval status
echo 		"<tr>";
echo 			"<td>Approval Status</td>";
echo			"<td>";

//check if bulk comm has first level approval
if ($this->objBulkSendRequest->fk_cancelled_user_id > 0)
{
	echo "Cancelled";
} else {
	if ($this->objBulkSendRequest->fk_approved_user_id < 1)
	{
		echo "Requires user approval";
	} elseif ($this->objBulkSendRequest->fk_approved_user_id > 0 && $this->objBulkSendRequest->fk_approved_admin_user_id < 1) {
		echo "Requires Administrator Approval<br/>";
		//load user details
		$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_approved_user_id);
		echo "Approved by " . $objUser->get("uname") . " (" . $objUser->get("fname") . " " . $objUser->get("sname") . ") on " . $this->objBulkSendRequest->datetime_approved;
	} elseif ($this->objBulkSendRequest->fk_approved_user_id > 0 && $this->objBulkSendRequest->fk_approved_admin_user_id > 0) {
		echo "Approved<br/>";
		//load user details
		$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_approved_user_id);
		echo "Approved by " . $objUser->get("uname") . " (" . $objUser->get("fname") . " " . $objUser->get("sname") . ") on " . $this->objBulkSendRequest->datetime_approved . "<br/>";

		//load admin details
		$objUser = $this->model_front_comms_bulk_send->fetchUser($this->objBulkSendRequest->fk_approved_admin_user_id);
		echo "Admin Approval by " . $objUser->get("uname") . " (" . $objUser->get("fname") . " " . $objUser->get("sname") . ") on " . $this->objBulkSendRequest->datetime_approved;
	}//end
}//end if

echo 			"</td>";
echo 		"</tr>";

//display request status
echo 		"<tr>";
echo 			"<td>Sending Status</td>";
echo 			"<td>";

if ($this->objBulkSendRequest->fk_cancelled_user_id > 0)
{
	echo "Cancelled";
} else {
	if ($this->objBulkSendRequest->datetime_started == "0000-00-00 00:00:00")
	{
		if ($this->objBulkSendRequest->fk_approved_user_id > 0 && $this->objBulkSendRequest->fk_approved_admin_user_id > 0)
		{
			echo "Waiting";
		} else {
			echo "Awaiting Approval";
		}//end if
	} elseif ($this->objBulkSendRequest->datetime_started != "0000-00-00 00:00:00" && $this->objBulkSendRequest->datetime_ended == "0000-00-00 00:00:00") {
		echo "In Progress";
	} elseif ($this->objBulkSendRequest->datetime_ended != "0000-00-00 00:00:00") {
		echo "Completed";
	}//end if
}//end if

echo 			"</td>";
echo 		"</tr>";

//display contacts selected
echo 		"<tr>";
echo 			"<td>Contacts Allocated</td>";
echo 			"<td>" . (int) $this->objBulkSendRequest->num_allocated . "</td>";
echo 		"</tr>";
echo 	"</table>";
echo "</fieldset>";
?>
</div>
<div class="mj3_forms clearfix">
<?php

echo "<fieldset><h4>Send Criteria</h4>";

$form = $this->form;
$form->prepare();
$html = $this->renderSystemFormHelper($form, $this, array("generate_field_groups" => TRUE, "enable_accordion" => TRUE));

//do some hacking to append content to the form
$html = str_replace('</form>', '', $html);
echo $html;

echo "</fieldset>";

echo "<fieldset><h4>Options</h4>";

echo 	"<span class=\"bulk_send_options\">Begin with &nbsp;</span>";

if ($this->objBulkSendRequest->get("allocate_new") == "0")
{
	$checked = "checked=\"checked\"";
} else {
	$checked = "";
}//end if
echo 	"<input type=\"radio\" name=\"allocate_new\" id=\"allocate_new\" value=\"0\"/ $checked>&nbsp;Oldest&nbsp;";

if ($this->objBulkSendRequest->get("allocate_new") == "1")
{
	$checked = "checked=\"checked\"";
} else {
	$checked = "";
}//end if
echo 	"<input type=\"radio\" name=\"allocate_new\" id=\"allocate_new\" value=\"1\"/ $checked>&nbsp;Newest";
echo 	"<br/>";

echo 	"<span class=\"bulk_send_options\">Start All &nbsp;</span>";

if ($this->objBulkSendRequest->get("allocate_all") == "1" && $this->objBulkSendRequest->get("allocate_num") == "")
{
	$checked = "checked=\"checked\"";
} else {
	$checked = "";
}//end if

if (is_numeric($this->objBulkSendRequest->get("allocate_num")))
{
	$allocate_num_value = $this->objBulkSendRequest->get("allocate_num");
} else {
	$allocate_num_value = "";
}//end if

echo 	"<input type=\"hidden\" name=\"allocate_all\" value=\"0\"/>";
echo 	"<input type=\"checkbox\" name=\"allocate_all\" id=\"allocate_all\" value=\"1\" $checked/>&nbsp;<span style=\"\">OR</span>&nbsp;";
echo 	"<input type=\"text\" name=\"allocate_num\" id=\"allocate_num\" value=\"$allocate_num_value\"/ style=\"width: 100px;\">&nbsp;of <span style=\"font-weight: bold;\">" . $this->objBulkSendRequest->get("send_total") . "</span>&nbsp;Contacts";
echo 	"<br/>";

// echo 	"<span class=\"bulk_send_options\">I agree to the terms and conditions</span>&nbsp;";
// echo 	"<input type=\"checkbox\" name=\"terms\" id=\"terms\" value=\"1\"/>";
echo "</fieldset><br/>";

//only display approval and update where first level approval has not taken place yet
if ($this->objBulkSendRequest->get("fk_approved_user_id") == "0" || $this->objBulkSendRequest->get("fk_approved_user_id") == "")
{
	echo "<input type=\"submit\" class=\"btn btn-primary\" value=\"Update\" name=\"submit_update\"/>&nbsp;";
	echo "<input type=\"submit\" value=\"Request Approval\" class=\"btn btn-success\" name=\"request_approval\"/>&nbsp;";
} elseif (is_numeric($this->objBulkSendRequest->get("fk_approved_user_id")) && $this->objBulkSendRequest->get("fk_approved_user_id") != "0" && ($this->objBulkSendRequest->get("fk_approved_admin_user_id") == "0" || $this->objBulkSendRequest->get("fk_approved_admin_user_id") == "")) {
	//display cancel option only where approval has been requested
	echo "<input type=\"submit\" value=\"Cancel Approval\" class=\"btn btn-danger\" name=\"cancel_approval\"/>&nbsp;";
}//end if

//only display delete option where request is not fully approved, and sending has not been completed
if ($this->objBulkSendRequest->get("fk_approved_admin_user_id") > 0 && $this->objBulkSendRequest->get("datetime_ended") != "0000-00-00 00:00:00")
{
	//sending completed
	echo "<input type=\"submit\" value=\"Delete Request\" class=\"btn btn-danger\" name=\"delete_request\" id=\"delete_request\"/>";
} elseif ($this->objBulkSendRequest->get("fk_approved_admin_user_id") < 1) {
	//not approved yet
	echo "<input type=\"submit\" value=\"Delete Request\" class=\"btn btn-danger\" name=\"delete_request\" id=\"delete_request\"/>";
} //end if
echo "</form>";

echo "</div></div>";//mj3_tables closing div and mj3_forms closing div