<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_PANELS_HTML .'&nbsp; Profile Panels - Delete Panel'); ?>

	<div class="mj3_forms clearfix">

		<form method="post">

			<h3>Are you sure you want to remove the '<?php echo $this->objPanel->get("name"); ?>' panel?<br />

			This action cannot be undone and any users using this panel will not be able to use it any longer.</h3>

			<input type="submit" name="delete" value="Yes" class="btn btn-danger">
			<input type="submit" value="Cancel" class="btn btn-default">

		</form>

	</div>

</div>
