<div class="mj3_tables clearfix">
	<?php echo $this->renderStandardViewHeader(ICON_LARGE_PANELS_HTML.'&nbsp; Delete Communication Look and Feel'); ?>
	<div class="mj3_forms clearfix">


		<form method="post">

			<h3>Are you sure you want to delete this Html template?<br />This action cannot be undone.</h3>

			<input type="submit" name="delete" value="Yes" class="btn btn-danger"/>
			<input type="submit" value="Cancel" class="btn btn-success"/>

		</form>

	</div>
</div>