<?php
echo "<a href=\"" . $this->url("front-power-tools/profile-automation", array("action" => "queue")) . "\" title=\"Trigger Communication Queuing Process\">Queue Communications</a><br/>";
echo "<a href=\"" . $this->url("front-power-tools/profile-automation", array("action" => "send")) . "\" title=\"Trigger Communication Sending Process\">Send Communications</a><br/>";
echo "<a href=\"" . $this->url("front-power-tools/profile-automation", array("action" => "queue-send")) . "\" title=\"Trigger Communication Queuing and Sending Process\">Queue and Send Communications</a><br/>";
echo "<a href=\"" . $this->url("front-power-tools/profile-automation", array("action" => "profile-activity")) . "\" title=\"Trigger Profile Activity Processing\">Process Profile Activity</a><br/>";
echo "<a href=\"" . $this->url("front-power-tools/profile-automation", array("action" => "user-activity")) . "\" title=\"Trigger User Activity Processes\">Process User Activity</a><br/>";