<div class="mj3_tables clearfix">
	<?php echo $this->renderStandardViewHeader(ICON_LARGE_LIST_HTML .'&nbsp; Delete Task');  ?>
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-users-tasks", array("user_id" => $this->user_id)); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>
	<div class="mj3_forms clearfix">
		<form method="post">
		<h3>Are you sure you want to delete this task?<br />This action cannot be undone.</h3>
			<input type="submit" value="Yes" name="delete" class="btn btn-danger"/>
			<input type="submit" value="Cancel" class="btn btn-success"/>
		</form>
	</div>

</div>

