<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_COMMS_HTML . '&nbsp; Bulk Send Criteria'); ?>
<ul class="nav nav-tabs">
	<li role="presentation"><a href="<?php echo $this->url("front-comms-bulksend"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
</ul>
<div class="mj3_table_contain clearfix">
<?php
//display journey data
echo 	"<h3>Journey to be sent: <a href=\"" . $this->url("front-comms-admin/journeys", array("id" => $this->objJourney->get("id"), "action" => "edit")) . "\" title=\"Update Journey\" data-toggle=\"tooltip\">" . $this->objJourney->get("journey") . "</a></h3>";
echo 	"<div id=\"journey-details-summary\">";
echo 		"<p>Description : " . $this->objJourney->get("description") . "</p>";
if ($this->objJourney->isExpired() === TRUE)
{
	echo 		"<p style=\"padding: 7px;\" class=\"text-danger bg-danger\">Warning: This journey has expired</p>";
}//end if

echo 	"</div>";
echo 		"<h4>Communications</h4>";
echo 		"<table class=\"table-simple-style data-table mj3-table table table-striped dataTable\" width=\"100%\">";
echo 			"<tr>";
echo 				"<th>Number</th>";
echo 				"<th>Type</th>";
echo 				"<th>Expires</th>";
echo 				"<th>Active</th>";
echo 				"<th>&nbsp;</th>";
echo 			"<tr>";

foreach ($this->objJourney->get("comms") as $objComm)
{
	echo	 "<tr>";
	echo 		"<td>" . $objComm->comm_num . "</td>";
	echo 		"<td>" . $objComm->comm_via_data_comm_via . "</td>";
	echo 		"<td>" . $objComm->date_expiry . "</td>";

	if ($objComm->active == 1)
	{
		echo 	"<td>" . ICON_SMALL_ACTIVE_HTML . "</td>";
	} else {
		echo 	"<td>" . ICON_SMALL_INACTIVE_HTML . "</td>";
	}//end if

	echo 		"<td><a href=\"" . $this->url("front-comms-admin/comms", array("journey_id" => $this->objJourney->get("id"), "id" => $objComm->id, "action" => edit)) . "\" title=\"Edit Communication\" data-toggle=\"tooltip\">" . ICON_SMALL_MODIFY_HTML . "</a>";

	echo 	"</tr>";
}//end foreach

?>
		</table>
	</div><!-- mj3_table_contain closing div -->
	<div class="mj3_forms clearfix">
	<!-- Load bulk send javascript file -->
	<script type="text/javascript" src="/js/bulksend/general.js"></script>
<?php
	$form = $this->form;
	$form->prepare();
	echo $this->renderSystemFormHelper($form, $this, array("generate_field_groups" => TRUE, "enable_accordion" => TRUE));
?>

	</div><!-- mj3_forms clearfix -->
</div>

