<?php 
//add editor js
echo $this->headScript()->appendFile($this->layout()->cdn_url . '/js/vendor/tinymce/tinymce.min.js');
echo $this->headScript()->appendFile($this->layout()->cdn_url . '/js/vendor/tinymce/jquery.tinymce.min.js');
?>
<script type="text/javascript">
	jQuery(document).ready(function () {
		//check the populate form checkbox
		jQuery("#populate_form").attr("checked", "checked");
		//check the active form checkbox
		jQuery("#active").attr("checked", "checked");

		//start text editors
		jQuery.mj_text_editor({
			element: jQuery("#copy") //content above form
		});

		jQuery.mj_text_editor({
			element: jQuery("#terms") //terms and conditions
		});

		jQuery.mj_text_editor({
			element: jQuery("#copy2") //content below form
		});

		jQuery.mj_text_editor({
			element: jQuery("#submit_copy") //post submit content
		});

		jQuery.mj_text_editor({
			element: jQuery("#reject_copy")
		});

		jQuery.mj_text_editor({
			element: jQuery("#_notify_copy") //notification content
		});
	});
</script>
<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_FORMS_HTML .'&nbsp; Create Form'); ?>
<?php
//load session for plugins enabled
$objUserSession = \FrontUserLogin\Models\FrontUserSession::isLoggedIn();
$arr_plugins = (array) $objUserSession->profile->plugins_enabled;
?>
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-form-admin/form"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
		<li role="presentation"><a href="<?php echo $this->url("front-form-admin/form", array("action" => "create-form")); ?>?ftype=cpp" title="Create a Contact Profile Form" data-toggle="tooltip">Create Contact Profile Form</a></li>

		<?php if (!is_array($arr_plugins) || (is_array($arr_plugins) && in_array("sales_funnels", $arr_plugins))) : ?>
			<li role="presentation"><a href="<?php echo $this->url("front-form-admin/form", array("action" => "create-form")); ?>?ftype=tracker" title="Create a Tracker" data-toggle="tooltip">Create Tracker Form</a></li>
		<?php endif;?>
	</ul>

	<div class="mj3_forms clearfix">

		<?php
			//add forms admin js
			echo $this->headScript()->appendFile($this->basePath() . '/js/includes/forms-admin.js');

			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this, array("enable_accordion" => TRUE, "generate_field_groups" => TRUE));
		?>

	</div>

</div>