<div class="mj3_tables clearfix">

	<script type="text/javascript">
		jQuery(document).ready(function () {
			//activate behaviours views
			jQuery(".behaviours_view").mj_behaviours_view();

			jQuery(".ajax-dropdown").change(function () {
				if (jQuery(this).val() == "_load_data_")
				{
					loadSearchFormData(jQuery(this).attr("id"), jQuery(this));
				}//end if
			});

			//monitor quick search button
			jQuery(".quick-search-button").click(function (e) {
				e.preventDefault();

				//populate values into search form
				jQuery("#search-form").find("#forms_form").val(jQuery("#quick-search-keyword").val());

				//submit the form
				jQuery("#search-form").submit();
			});
		});

		function loadSearchFormData(param, element)
		{
			//set element data
			element.empty();
			element.append(jQuery("<option></option>").text("--loading--"));

			var param_url = "<?php echo $this->url("front-form-admin/form", array("action" => "ajax-search-values")) . "?param=#param";?>";

			//request data
			jQuery.ajax({
				url: param_url.replace("#param", param),
			})
			.done(function (data) {
				var objData = jQuery.parseJSON(data);

				if (objData.error == 1)
				{
					//reset element
					element.append(jQuery("<option></option>").text("--select--"));
					element.append(jQuery("<option></option>").val("_load_data_").text("--select--"));
					alert("An error occured: " + objData.response);
					return false;
				}//end if

				element.empty();
				element.append(jQuery("<option></option>").val("").text("--select--"));
				jQuery.each(objData.response, function (i, obj) {
					element.append(jQuery("<option></option>").val(obj.id).text(obj.val));
				});
			})
			.fail(function () {
				alert("Data could not be loaded. An unkown error has occured");
				return false;
			});
		}//end function
	</script>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#form-search-form">
					<span class="sr-only">Toggle navigation</span>

				</button>

				<span class="navbar-brand">
					<?php echo ICON_LARGE_FORMS_HTML; ?>&nbsp;
					My Forms
				</span>
			</div>

			<div class="navbar-collapse" id="form-search-form">
				<form class="navbar-form navbar-right form-inline" role="search">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Quick search" id="quick-search-keyword" value="<?php if ($this->arr_params["keyword"] != "") {echo $arr_params["keyword"];}?>">
					</div>
					<button type="submit" class="btn btn-primary quick-search-button">Search</button>
					<a class="btn btn-default" data-toggle="collapse" data-target="#advsearch" aria-expanded="false" aria-controls="advsearch">Advanced</a>
				</form>
			</div>

			<div class="collapse" id="advsearch">
				<div class="well clearfix">
					<form method="post" id="search-form">
						<div class="form-group">
							<label for="forms_form">Title:</label>
							<input type="text" class="form-control" name="forms_form" id="forms_form" placeholder="e.g. Web Form x" value="<?php if ($this->arr_params["forms_form"] != "") {echo $arr_params["forms_form"];}?>"/>
						</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="forms_type_id">Type:</label>
									<select name="forms_type_id" id="forms_type_id" class="ajax-dropdown form-control">
										<option value="">--select--</option>
										<option value="_load_data_">Load Data</option>
									</select>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="forms_active">Status:</label>
									<select name="forms_active" id="forms_active" class="ajax-dropdown form-control">
										<option value="">--select--</option>
										<option value="1">Active</option>
										<option value="0">Inactive</option>
									</select>
								</div>
							</div>
						<input type="submit" value="Search" class="btn btn-primary pull-right"/>
					</form>
				</div>
			</div>
		</div>
	</nav>

	<ul class="nav nav-tabs">
		<li class="mj3_btnchangeform"><a href="<?php echo $this->url("front-form-admin/form", array("action" => "create-form")); ?>" title="Create a new form" data-toggle="tooltip" class="btn btn-success"><?php echo ICON_LARGE_ADD_HTML .'&nbsp;Add Form'; ?></a></li>
	</ul>

	<div class="mj3_table_contain">

		<?php
		//load session for plugins enabled
		$objUserSession = \FrontUserLogin\Models\FrontUserSession::isLoggedIn();
		$arr_plugins = (array) $objUserSession->profile->plugins_enabled;

		foreach ($this->objForms as $objForm)
		{
			if (!isset($objForm->id))
			{
				continue;
			}//end if

			$arr_form["name"] = $objForm->form;
			switch (strtolower(str_replace(" ", "", $objForm->form_types_form_type)))
			{
				case "salesfunnel":
					$arr_form["form_type"] = "Tracker";
					break;

				default:
					$arr_form["form_type"] = $objForm->form_types_form_type;
					break;
			}//end switch


			if ($objForm->active == 1)
			{
				$arr_form["active_url"] = ICON_SMALL_ACTIVE_HTML;
			} else {
				$arr_form["active_url"] = ICON_SMALL_INACTIVE_HTML;
			}//end if

			switch ($objForm->form_types_behaviour)
			{
				case "__web":
				case "web":
				case "__viral":
				case "viral":
					$preview_url = "<a href=\"" . $this->url("majestic-external-forms/bf", array("fid" => $objForm->id)) . "\" target=\"__blank\" title=\"Preview Form\" data-toggle=\"tooltip\">" . ICON_SMALL_SEARCH_HTML . "</a>";

					if (in_array("behaviours_basic", $arr_plugins) || in_array("behaviours_advanced", $arr_plugins))
					{
						$behaviours_url = "<a href=\"" . $this->url("front-form-admin/form", array("action" => "form-behaviours", "id" => $objForm->id)) . "?form_id=" . $objForm->id . "\" title=\"Configure Form Behaviours\"  data-toggle=\"tooltip\" class=\"behaviours_view\">" . ICON_SMALL_BEHAVIOURS_HTML . "</a>";
					} else {
						$behaviours_url = "";
					}//end if

					//set urls
					$edit_url = "<a href=\"" . $this->url("front-form-admin/form", array("action" => "edit-form", "id" => $objForm->id)) . "\" title=\"Edit Form\" data-toggle=\"tooltip\" class=\"page-e-link\">" . ICON_SMALL_MODIFY_HTML . "</a>";
					break;

				case "__sales_funnel":
				case "__tracker":
				case "tracker":
					if (in_array("behaviours_basic", $arr_plugins) || in_array("behaviours_advanced", $arr_plugins))
					{
						$behaviours_url = "<a href=\"" . $this->url("front-form-admin/form", array("action" => "form-behaviours", "id" => $objForm->id)) . "?form_id=" . $objForm->id . "&behaviour=form_sales_funnel\" title=\"Configure Tracker Behaviours\" data-toggle=\"tooltip\" class=\"behaviours_view\">" . ICON_SMALL_BEHAVIOURS_HTML . "</a>";
					} else {
						$behaviours_url = "";
					}//end if

					//use preview url as sales funnel advanced settings url
					//$preview_url = "<a href=\"" . $this->url("front-form-admin/sales-funnel", array("action" => "sf-advanced-settings", "id" => $objForm->id)) . "?form_id=" . $objForm->id . "\" title=\"Configure advanced Tracker Options\" data-toggle=\"tooltip\" class=\"\">" . ICON_SMALL_SETTINGS_HTML . "</a>";
					$preview_url = "";
					//set urls
					$edit_url = "<a href=\"" . $this->url("front-form-admin/form", array("action" => "edit-form", "id" => $objForm->id)) . "?ftype=tracker\" title=\"Edit Form\" data-toggle=\"tooltip\" class=\"page-e-link\">" . ICON_SMALL_MODIFY_HTML . "</a>";
					break;

				case "__cpp":
				case "cpp":
					//set urls
					$edit_url = "<a href=\"" . $this->url("front-form-admin/form", array("action" => "edit-form", "id" => $objForm->id)) . "?ftype=cpp\" title=\"Edit Form\" data-toggle=\"tooltip\" class=\"page-e-link\">" . ICON_SMALL_MODIFY_HTML . "</a>";
					$preview_url = "";
					break;

				default:
					$preview_url = "";
					break;
			}//end switch

			$delete_url = "<a href=\"" . $this->url("front-form-admin/form", array("action" => "delete-form", "id" => $objForm->id)) . "\" title=\"Delete Form\" data-toggle=\"tooltip\" class=\"\">" . ICON_SMALL_DELETE_HTML . "</a>";
			$arr_form["urls"] = $edit_url . "&nbsp;" . $behaviours_url . "&nbsp;" . $preview_url . "&nbsp;" . $delete_url;
			$arr[] = $arr_form;
		}//end function

		$css_id = str_replace(".", "", microtime(TRUE));
		echo $this->renderDataTableHelper(array("return_script" => TRUE), $css_id);
		echo $this->renderSimpleHTMLTable($arr, array("Form", "Type", "Active", $add_url), array("id" => $css_id));
		?>

	</div>

</div>

<div id="manage-behaviours-section" class="modal fade">

</div>
