<?php 
if (isset($this->postData) && is_array($this->postData))
{
	?>
	<div class="mj3-loginbox">
		<div class="blueprint-blue">
			<?php if (isset($this->returnText) && $this->returnText != '')
			{
				echo '<p>' . $this->returnText . '</p>';
			} else {
				echo '<p>Your request is being processed, please monitor your inbox for an email with further details.</p><p>Should the email not arrive, please contact your profile administration for assistance.</p>';
			}//end if
			?>
		</div>
	</div>
	<?php 
} else {
?>
<div class="mj3-loginbox">
	<div class="blueprint-blue">
		<h4>Password Reset</h4>
		<form id="password-reset" class="user-login-form" name="password-reset" method="post" action="">
			<div class="form-group">
				<input type="text" class="form-control" title="Enter your username for the profile" placeholder="Username" required="required" id="uname" name="uname" value="">
			</div>

			<div class="form-group">
				<input type="email" class="form-control" title="Enter the email address for your user account" placeholder="Email address" required="required" id="email" name="email" value="">
			</div>

			<input type="submit" class="btn btn-primary" value="Submit">
		</form>
	</div>
</div>

<?php 
}//end if
if (isset($this->layout()->app_config["login_page_settings"]["google_analytics_code"]) && $this->layout()->app_config["login_page_settings"]["google_analytics_code"] != '' && $this->layout()->app_config["login_page_settings"]["google_analytics_status"] === TRUE):?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo $this->layout()->app_config["login_page_settings"]["google_analytics_code"]?>', 'auto');
  ga('send', 'pageview');

</script>
<?php endif;?>
