<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_LOCATION_HTML .'&nbsp;Cities'); ?>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-locations"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>

	<div class="mj3_table_contain clearfix">

		<?php

		/**
		 * Prepare data
		 */
		foreach ($this->objCities as $objCity)
		{
			if (!isset($objCity->id))
			{
				continue;
			}//end if

			$arr_data["city"] = $objCity->city;

			if ($objCity->active == 1)
			{
				$arr_data["active"] = ICON_SMALL_ACTIVE_HTML;
			} else {
				$arr_data["active"] = ICON_SMALL_INACTIVE_HTML;
			}//end if

			$arr_data["province"] = $objCity->province;

			$arr[] = $arr_data;
		}//end foreach

		$css_id = str_replace(".", "", microtime(TRUE));
		echo $this->renderDataTableHelper(array("return_script" => TRUE), $css_id);
		echo $this->renderSimpleHTMLTable($arr, array("City", "Active", "Province"), array("id" => $css_id));
		?>

	</div>

</div>