<div class="mj3_tables clearfix">
	<?php echo $this->renderStandardViewHeader(ICON_LARGE_LOCATION_HTML .'&nbsp;Locations'); ?>

	<div class="mj3_table_contain clearfix">

		<?php
		echo "<h4><a href=\"" . $this->url("front-locations/countries") . "\" title=\"Countries\" data-toggle=\"tooltip\">Countries</a></h4>";
		echo "<h4><a href=\"" . $this->url("front-locations/provinces") . "\" title=\"Provinces\" data-toggle=\"tooltip\">Provinces</a></h4>";
		echo "<h4><a href=\"" . $this->url("front-locations/cities") . "\" title=\"Cities\" data-toggle=\"tooltip\">Cities</a></h4>";
		//echo "<h4><a href=\"" . $this->url("front-locations/custom-cities") . "\" title=\"Custom Cities\" data-toggle=\"tooltip\">Custom Cities</a></h4>";
		?>

	</div>

</div>