<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_SMS_HTML . '&nbsp;Create SMS Campaign'); ?>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-links"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>

	<div class="mj3_forms clearfix">
		<?php
			$form = $this->form;
			$form->setAttribute("action", $this->url("front-comms-sms-campaigns", array("action" => "create")));
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this);

		?>
	</div>
</div>
