<script type="text/javascript">
	jQuery(document).ready(function () {
		//request contact data
		<?php if (isset($this->reg_id) && $this->reg_id != "" && $this->form_posted !== TRUE) : ?>
		loadContact();
		<?php endif;?>

		//bootstrap form
		jQuery(".form-element").addClass("form-group");
	});

	<?php if (isset($this->reg_id) && $this->reg_id != "" && $this->form_posted !== TRUE) : ?>
	function loadContact()
	{
		var form = jQuery(".form").serialize();
		jQuery.ajax({
			url: "/forms/ajax-load-contact",
			type: "post",
			data: form + "&r=<?php echo $this->reg_id;?>&f=<?php echo $this->form_id;?>",
		})
		.done(function (data) {
			var objData = jQuery.parseJSON(data);

			if (objData.error == 1)
			{
				console.log(objData.response);
				return false;
			}//end if

			//populate the form fields
			jQuery.each(objData.response, function (field, value) {
				//deal with text fields
				if (jQuery("#" + field).is("input:text"))
				{
					if (jQuery("#" + field).val() == "")
					{
						jQuery("#" + field).val(value);
					}//end if
				}//end if

				//deal with checkboxes
				if (jQuery("#" + field).is("input:checkbox"))
				{
					if (value == 1)
					{
						jQuery("#" + field).prop("checked", true);
					}//end if
				}//end if

				//deal with radios
				if (jQuery("#" + field).is("input:radio"))
				{
					if (jQuery("input:radio:checked[name='" + field + "']").length == 0)
					{
						jQuery("input:radio[name='" + field + "']").filter("[value='" + value + "']").prop("checked", true);
					}//end if
				}//end if

				//deal with teaxtareas
				if (jQuery("#" + field).is("textarea"))
				{
					if (jQuery("#" + field).val() == "")
					{
						jQuery("#" + field).val(value);
					}//end if
				}//end if

				//deal with dropdowns
				if (jQuery("#" + field).is("select"))
				{
					if (jQuery("#" + field).val() == "")
					{
						jQuery("#" + field).val(value);
					}//end if
				}//end if
			});
		})
		.fail(function (data) {
			//console.log("Error collection form data");
			//console.log(data);
		});
	}//end function
	<?php endif;?>
</script>

<?php
//check look and feel css file
if (isset($this->objLookAndFeel) && $this->objLookAndFeel->css_file != "")
{
	echo '<link href="' . $this->objLookAndFeel->css_file . '" media="screen" rel="stylesheet" type="text/css">';
}//end if
?>

<div class="mj3_tables clearfix">
	<div class="mj3_webform">

		<?php
			//add forms widget
			echo $this->headScript()->appendFile($this->basePath() . '/js/plugins/mj-forms-widgets.js');
			$form = $this->form;
			$form->prepare();

			if (isset($this->additional_data["cid"]) && is_object($this->objContact) && $this->objFormRawData->show_fwd_warn == 1)
			{
				$contact_html = "<p><a href=\"" . $this->form_url . "\">Click here if you are not " . $this->objContact->fname . " " . $this->objContact->sname . "</a></p>";
			} else {
				$contact_html = "";
			}//end if

			if (isset($this->objLookAndFeel)) {
				$html = $this->objLookAndFeel->content;
				$html = str_replace("#content", $contact_html . $this->renderExternalFormHelper($this->objFormRawData, $form, $this), $html);
				echo $html;
			} else {
				echo $contact_html . $this->renderExternalFormHelper($this->objFormRawData, $form, $this);
			} //end if
		?>

	</div>

</div>