<div class="mj3_tables clearfix">
	<?php echo $this->renderStandardViewHeader(ICON_LARGE_SYNC_HTML .'&nbsp; Delete a Replace Field'); ?>
	<div class="mj3_forms clearfix">
		<form method="post">
			<h3>This will permanently delete the Replace Field. This action cannot be undone. <br /> Are you sure you want to delete this Replace Field?</h3>
				<input type="submit" name="delete" value="Yes" class="btn btn-danger"/>
				<input type="submit" name="delete" value="Cancel" class="btn btn-success"/>
		</form>
	</div>
</div>
