<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_WEBHOOK_HTML .'&nbsp; Manage Webhooks - Create Webhook'); ?>
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-power-tools/webhooks"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>
	<div class="mj3_forms clearfix">
		<?php
			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this);
		?>
	</div>
</div>




