<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_WEBHOOK_HTML .'&nbsp; Manage Webhooks - Delete Webhook'); ?>

	<div class="mj3_forms clearfix">
		<form method="post">
			<h3>Are you sure you want to delete the "<?php echo $this->objWebhook->get("title");?>" webhook?<br />This action cannot be undone.</h3>
			<input type="submit" name="delete" value="Yes" class="uk-button uk-button-danger"/>
			<input type="submit" value="Cancel" class="uk-button uk-button-success"/>
		</form>
	</div>
</div>


