<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_WEBHOOK_HTML .'&nbsp; Manage Webkooks - Edit Header'); ?>
	<ul class="nav nav-tabs">
		<li role="presentation"><a href="<?php echo $this->url("front-power-tools/webhooks", array("action" => "webhook-headers")) . "?webhook_id=" . $this->objWebhook->get("id"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
	</ul>
	<div class="mj3_forms clearfix">
		<?php
			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this);
		?>
	</div>
</div>