<div class="mj3_table clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_SYNC_HTML .'&nbsp; Delete Recurring Event'); ?>
	<div class="mj3_forms clearfix">
		<form method="post">
		<h3>Are you sure you want to delete this trigger?<br />This action cannot be undone.</h3>
			<input type="submit" name="delete" value="Yes" class="btn btn-danger"/>
			<input type="submit" value="Cancel" class="btn btn-success"/>
		</form>
	</div>
</div>
