<div class="mj3_tables clearfix">
<?php echo $this->renderStandardViewHeader(ICON_LARGE_SYNC_HTML .'&nbsp; Edit Recurring Event'); ?>
<ul class="nav nav-tabs">
	<li role="presentation"><a href="<?php echo $this->url("front-comms-admin/dates"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
</ul>
	<div class="mj3_forms clearfix">
		<?php
			$form = $this->form;
			$form->setAttribute("action", $this->url("front-comms-admin/dates", array("action" => "edit", "id" => $this->objCommDate->id)));
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this);
		?>
	</div>
</div>


