<div class="mj3_tables clearfix">
	<?php echo $this->renderStandardViewHeader(ICON_LARGE_FIELDS_HTML .'&nbsp; Delete a Generic Field'); ?>

	<ul class="nav nav-tabs">
		<li role="presentation"><?php echo "<a href=\"" . $this->url("front-form-admin/generic-fields") . "\" title=\"Back\" data-toggle=\"tooltip\">" . ICON_MEDIUM_BACK_HTML . "</a>"; ?></li>
	</ul>
	<div class="mj3_forms clearfix">
		<form method="post">
			<h3>This will permanently delete the Generic Field. This action cannot be undone.<br />
				Are you sure you want to delete this Generic Field?</h3>
			<input type="submit" name="delete" value="Yes" class="btn btn-danger"/>
			<input type="submit" value="Cancel" class="btn btn-success"/>
		</form>
	</div>
</div>



