<div class="mj3_tables clearfix">
	<?php echo $this->renderStandardViewHeader(ICON_LARGE_FIELDS_HTML .'&nbsp; Edit Generic Field'); ?>

	<div class="mj3_forms clearfix">
		<ul class="nav nav-tabs">
			<li role="presentation"><a href="<?php echo $this->url("front-form-admin/generic-fields"); ?>" title="Back" data-toggle="tooltip"><?php echo ICON_MEDIUM_BACK_HTML; ?></a></li>
		</ul>
		<?php
			$form = $this->form;
			$form->prepare();
			echo $this->renderSystemFormHelper($form, $this);
		?>
	</div>
</div>
